#!/bin/bash

# This script gets you a working shell in the docker environment spawned by VS code.

# 🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦
# https://github.com/microsoft/vscode-remote-release/issues/2485
# 🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦

devcontainer_id=$(docker ps -aqf "label=devcontainer.local_folder=$(pwd)")
if [ -n "$devcontainer_id" ]; then
  exec docker exec -e TERM -it "$devcontainer_id" sudo -u human zsh -l
else
  exec docker compose exec --user human dev zsh -l
fi
